### ISSUE TITLE
Python 3.10 Import Error

### ISSUE THREAD

**Issue by evan-palmer** [loco-3d/crocoddyl#1258]
## Bug description

While attempting to import Crocoddyl in a script using Python 3.10, the following error is raised:

```
Traceback (most recent call last):
  File "/workspaces/bravo-mpc/bravo-mpc/sim.py", line 4, in <module>
    from control.mpc import make_controller_from_config
  File "/workspaces/bravo-mpc/bravo-mpc/control/mpc.py", line 11, in <module>
    import crocoddyl
  File "/usr/local/lib/python3.10/dist-packages/cmeel.prefix/lib/python3.10/site-packages/crocoddyl/__init__.py", line 7, in <module>
    from .libcrocoddyl_pywrap import *  # noqa
AttributeError: 'NoneType' object has no attribute '__dict__'. Did you mean: '__dir__'?
```

## Reproduction steps

Crocoddyl was installed using

```
python3 -m pip install crocoddyl
```

Then imported with

```
import crocoddyl
```

No additional steps are taken to receive this error. I can confirm that Pinocchio installs and runs correctly as well.

### System

- Python Version: 3.10
- OS: Docker image with Ubuntu 22.04 as the base image (relevant sample included for reproducability below)
- Crocoddyl version: Latest Python release available through PyPI

```dockerfile
FROM ubuntu:22.04

# Install system packages
RUN apt-get -q update \
  && apt-get -q -y upgrade \
  && apt-get -q install --no-install-recommends -y \
  git \
  cmake \
  lsb-release \
  curl \
  build-essential \
  python3 \
  python3-pip \
  sudo \
  libboost-all-dev \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Install robotpkg & pinocchio
RUN mkdir -p /etc/apt/keyrings \
  && curl http://robotpkg.openrobots.org/packages/debian/robotpkg.asc |tee /etc/apt/keyrings/robotpkg.asc \
  && echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/robotpkg.asc] http://robotpkg.openrobots.org/packages/debian/pub $(lsb_release -cs) robotpkg" | tee /etc/apt/sources.list.d/robotpkg.list \
  && apt-get -q update \
  && apt-get -q -y upgrade \
  && apt-get -q install --no-install-recommends -y \
  robotpkg-py3*-pinocchio \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PATH=/opt/openrobots/bin:$PATH
ENV PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
ENV LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
ENV PYTHONPATH=/opt/openrobots/lib/python3.10/site-packages:$PYTHONPATH
ENV CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH

# Install Python packages
RUN python3 -m pip install crocoddyl
```

**Comment by evan-palmer** [comment]
I was able to fix this just now by installing Pinocchio from PyPI rather than manually installing it as done in the Dockerfile shown.
