### ISSUE TITLE
Error in test_state when checking with free-flyer.

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#148]
In GitLab by @proyan on Mar 8, 2019, 14:19

I added the following test in test_state to check for the cases where there is a freeflyer in the state.

`class StatePinocchioFFTest(StateTestCase):  

from crocoddyl import loadTalosLegs  

rmodel = loadTalosLegs().model  

StateTestCase.NX = rmodel.nq + rmodel.nv  

StateTestCase.STATE = StatePinocchio(rmodel)  `

I get errors.

I'm investigating why this happens.

======================================================================
FAIL: test_velocity_from_Jintegrate_Jdiff (__main__.StatePinocchioFFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 126, in test_velocity_from_Jintegrate_Jdiff
    "Velocity computed from Jdiff is wrong.")
AssertionError: Velocity computed from Jdiff is wrong.

======================================================================
FAIL: test_integrate_against_difference (__main__.StatePinocchioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 36, in test_integrate_against_difference
    "Integrate function doesn't agree with difference rule.")
AssertionError: Integrate function doesn't agree with difference rule.

======================================================================
FAIL: test_velocity_from_Jintegrate_Jdiff (__main__.StatePinocchioTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 126, in test_velocity_from_Jintegrate_Jdiff
    "Velocity computed from Jdiff is wrong.")
AssertionError: Velocity computed from Jdiff is wrong.

======================================================================
FAIL: test_velocity_from_Jintegrate_Jdiff (__main__.StateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 126, in test_velocity_from_Jintegrate_Jdiff
    "Velocity computed from Jdiff is wrong.")
AssertionError: Velocity computed from Jdiff is wrong.

======================================================================
FAIL: test_integrate_against_difference (__main__.StateUnicycleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 36, in test_integrate_against_difference
    "Integrate function doesn't agree with difference rule.")
AssertionError: Integrate function doesn't agree with difference rule.

======================================================================
FAIL: test_velocity_from_Jintegrate_Jdiff (__main__.StateUnicycleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 126, in test_velocity_from_Jintegrate_Jdiff
    "Velocity computed from Jdiff is wrong.")
AssertionError: Velocity computed from Jdiff is wrong.

======================================================================
FAIL: test_integrate_against_difference (__main__.StateVectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 36, in test_integrate_against_difference
    "Integrate function doesn't agree with difference rule.")
AssertionError: Integrate function doesn't agree with difference rule.

======================================================================
FAIL: test_velocity_from_Jintegrate_Jdiff (__main__.StateVectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rbudhira/devel/src/loco3d/crocoddyl/unittest/test_state.py", line 126, in test_velocity_from_Jintegrate_Jdiff
    "Velocity computed from Jdiff is wrong.")
AssertionError: Velocity computed from Jdiff is wrong.

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 8, 2019, 15:19

mentioned in merge request !136

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 8, 2019, 15:19

!136 deals with this issue.

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 8, 2019, 15:19

closed
