### ISSUE TITLE
Action LQR is broken

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#153]
In GitLab by @nmansard on Mar 14, 2019, 12:16

When NX!=NU, ActionModelLQR does not work. Here is a feedback of test_solvers.py when LQR(3,2) is set:
Traceback (most recent call last):
  File "test_solvers.py", line 667, in <module>
    problem = ShootingProblem(model.State.zero()+1, [model]*T,model)
  File "/home/nmansard/src/crocoddyl/unittest/crocoddyl/shooting.py", line 12, in __init__
    self.runningDatas  = [ m.createData() for m in runningModels ]
  File "/home/nmansard/src/crocoddyl/unittest/crocoddyl/action.py", line 35, in createData
    return self.ActionDataType(self)
  File "/home/nmansard/src/crocoddyl/unittest/crocoddyl/action.py", line 184, in __init__
    self.Fu[:, :] = model.B
ValueError: could not broadcast input array from shape (2,2) into shape (2,3)

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 13:42

assigned to @cmastalli

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 14:04

mentioned in merge request !141

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 14:05

I will close this since it's solved in !141.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 14:05

closed

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 20, 2019, 14:31

reopened

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 20, 2019, 14:31

I will close after merging !141

**Comment by wxmerkt** [comment]
In GitLab by @nmansard on Mar 22, 2019, 09:16

mentioned in commit 65c178d851a4498d591eaed62c84f685632169ec

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 26, 2019, 16:41

closed
