### ISSUE TITLE
Unit-test locomotion is not passing

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#159]
In GitLab by @cmastalli on Mar 27, 2019, 13:27

It says that there is not module named locomotion when it calls the follows:
```python
from crocoddyl.locomotion import createPhiFromContactSequence
```

**Comment by wxmerkt** [comment]
In GitLab by @nmansard on Mar 28, 2019, 10:04

Thanks. I pushed the missing locomotion/__init__.py.

**Comment by wxmerkt** [comment]
In GitLab by @nmansard on Mar 28, 2019, 10:04

closed

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 28, 2019, 12:12

reopened

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 28, 2019, 12:16

For some reason, I am not able to load the xml file. I just compile the latest version of multicontact-api. This is the error message that appears when I run this unit-test:

```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)
```
@proyan do you know the reason?

---
Additionally the filepath is relative, this might be problematic for CI. I suggest to make it absolute. @nmansard would you handle this?

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 28, 2019, 12:20

Use the devel branch of multicontact-api.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 28, 2019, 12:39

It's still crashing after compiling the devel branch. I have this new error message:

```
Traceback (most recent call last):
  File "unittest/test_locomotion.py", line 30, in <module>
    assert(np.isclose(cc.com_vcom.eval(t)[0], x[:6,:], atol=eps).all())
  File "/home/cmastall/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 2531, in isclose
    x = x * ones_like(cond)
  File "/home/cmastall/.local/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 220, in __mul__
    return N.dot(self, asmatrix(other))
ValueError: shapes (6,1) and (6,1) not aligned: 1 (dim 1) != 6 (dim 0)
```

and I noticed that this happens when
```python
x[:6,:] is [NaN]*6
```
is there a problem in the xml file?

**Extra comment**
- We should rename multicontact-api master branch to something like legacy-master, and then aligned devel and master branches. @proyan do you agree with this? It's just weird to have a master branch on top of devel one.

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 28, 2019, 12:57

If the statetrajectory is NaN, there is a problem in the xml file. it should not be NaN

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 28, 2019, 16:24

Could you have a look on it? The problem appears in the devel branch

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 3, 2019, 09:59

mentioned in merge request !152

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 4, 2019, 15:06

mentioned in merge request !137

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 18, 2019, 08:33

This issue was solved in !152.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 18, 2019, 08:33

closed
