### ISSUE TITLE
Python unit-tests are passing even when it fails an assertion

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#224]
In GitLab by @cmastalli on Aug 8, 2019, 12:54

After changing the way of that I run multiple testcases, I noticed that `make test` doesn't detect a failure even when an assertion fails.

These are the changes for running multiple testcase:
```python
if __name__ == '__main__':
    test_classes_to_run = [StateVectorTest, StateMultibodyTest]
    loader = unittest.TestLoader()
    suites_list = []
    for test_class in test_classes_to_run:
        suite = loader.loadTestsFromTestCase(test_class)
        suites_list.append(suite)
    big_suite = unittest.TestSuite(suites_list)
    runner = unittest.TextTestRunner()
    results = runner.run(big_suite)
```

and when I added an intentional error. Let's say, I modified this line https://gepgitlab.laas.fr/loco-3d/crocoddyl/blob/cpp_devel/unittest/bindings/test_states.py#L32 to:
```python
        if self.STATE.__class__ == crocoddyl.libcrocoddyl_pywrap.StateMultibody:
            self.assertTrue(np.allclose(2*self.STATE.diff(x0, x1)[3:], self.STATE_DER.diff(x0, x1)[3:], atol=1e-9),
                            "state.diff() function doesn't agree with Python bindings.")
```

Then running `make test` doesn't detect the problem, i.e.
```bash
      Start 20: pybinds-states
20/24 Test #20: pybinds-states ...................   Passed    0.60 sec
      Start 21: pybinds-actions
21/24 Test #21: pybinds-actions ..................   Passed    0.59 sec
      Start 22: pybinds-shooting
22/24 Test #22: pybinds-shooting .................   Passed    0.59 sec
      Start 23: pybinds-solvers
23/24 Test #23: pybinds-solvers ..................   Passed    0.82 sec
      Start 24: pybinds-costs
24/24 Test #24: pybinds-costs ....................   Passed    0.67 sec

100% tests passed, 0 tests failed out of 24
```

but running `ctest -V` let us know what happens, i.e.:
```bash
20: Test command: /usr/bin/python "/devel/crocoddyl/unittest/bindings/test_states.py"
20: Environment variables: 
20:  PYTHONPATH=/devel/crocoddyl/build/bindings/python:/opt/ros/dls-distro/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/local/users/cmastall/lib/python2.7/dist-packages:/local/users/cmastall/lib/python2.7/site-packages:/opt/openrobots/lib/python2.7/dist-packages:/opt/openrobots/lib/python2.7/site-packages:/home/cmastall/.local/lib/python2.7/dist-packages:/home/cmastall/.local/lib/python2.7/site-packages
20: Test timeout computed to be: 1500
20: .......F..
20: ======================================================================
20: FAIL: test_python_derived_diff (__main__.StateMultibodyTest)
20: ----------------------------------------------------------------------
20: Traceback (most recent call last):
20:   File "/devel/crocoddyl/unittest/bindings/test_states.py", line 33, in test_python_derived_diff
20:     "state.diff() function doesn't agree with Python bindings.")
20: AssertionError: state.diff() function doesn't agree with Python bindings.
20: 
20: ----------------------------------------------------------------------
20: Ran 10 tests in 0.003s
20: 
20: FAILED (failures=1)
20/24 Test #20: pybinds-states ...................   Passed    0.59 sec
```

and we can also run manually this test, i.e.:
```bash
cmastall@yarisan:bindings$ python test_states.py 
.......F..
======================================================================
FAIL: test_python_derived_diff (__main__.StateMultibodyTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_states.py", line 33, in test_python_derived_diff
    "state.diff() function doesn't agree with Python bindings.")
AssertionError: state.diff() function doesn't agree with Python bindings.

----------------------------------------------------------------------
Ran 10 tests in 0.002s

FAILED (failures=1)
```

**This is very alarming problem, we can introduce bugs without detecting them in the CI**. I suspect there is a problem in the cmake submodule. @nim65s could you help me with this issue?

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 8, 2019, 13:02

changed the description

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 8, 2019, 13:02

assigned to @nim65s

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 8, 2019, 13:03

changed title from **Python unit-test are passing even when it fails an assertion** to **Python unit-test{+s+} are passing even when it fails an assertion**

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Aug 13, 2019, 13:25

@cmastalli could you commit / push that on a branch on your repo ?

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 14:27

I push these stuff inside topic/debug-ci (my forked repo).

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Aug 13, 2019, 16:52

This should be better: https://gepgitlab.laas.fr/cmastall/crocoddyl/merge_requests/1/diffs

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 17:05

mentioned in merge request !196

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 17:08

Thank @nim65s. I will continue fixing the other unit-tests

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 17:08

assigned to @cmastalli and unassigned @nim65s

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 17:34

mentioned in commit b4d69197b83bd1f8a8026cb85091801d8a5cee47

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Aug 13, 2019, 17:35

closed
