### ISSUE TITLE
Impulse legacy unittest sometimes fails

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#260]
In GitLab by @cmastalli on Sep 26, 2019, 11:19

It already happens twice after switching to new release of Pinocchio and EigenPy. This is the error message:

```bash
eigenpy warning: you use the deprecated class numpy.matrix without explicily asking for it. The default behaviour will change to numpy.array at next major release.
- Either call eigenpy.switchToNumpyMatrix() before using eigenpy to suppress this warning
- or call eigenpy.switchToNumpyArray() and adapt your code accordingly.
See https://github.com/stack-of-tasks/eigenpy/issues/87 for further details.
Traceback (most recent call last):
  File "/root/robotpkg/wip/py-crocoddyl/work.runner-991216bb-project-152-concurrent-2/crocoddyl-0.9.0/unittest/python/test_impact.py", line 132, in <module>
    NUMDIFF_MODIFIER * mnum.disturbance)  # threshold was 1e-3, is now 2.11e-4 (see assertNumDiff.__doc__)
  File "/root/robotpkg/wip/py-crocoddyl/work.runner-991216bb-project-152-concurrent-2/crocoddyl-0.9.0/unittest/python/testutils.py", line 23, in assertNumDiff
    raise NumDiffException("NumDiff exception, with residual of %.4g, above threshold %.4g" % (value, threshold))
testutils.NumDiffException: NumDiff exception, with residual of 0.0004294, above threshold 0.0002107
```

@jcarpent you might have some clue about it.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Nov 11, 2019, 23:00

closed

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Nov 11, 2019, 23:01

This code is deprecated and soon will be removed
