### ISSUE TITLE
Reformat, and enforce format, fix #125 - [merged]

### ISSUE THREAD

**Issue by wxmerkt** [loco-3d/crocoddyl#482]
In GitLab by @nim65s on Mar 11, 2019, 13:01

_Merges topic/format -> devel_

Hi,

This PR:
- heavily reformats all python files, with the help of tools like isort, flake8 & yapf.
- enforces this new format to be followed by a CI check.
- fixes the CI to run tests, in order to be sure that this reformatting did not break anything.

I had to make a few choices about the format, and they are documented in the `setup.cfg` file.

The most obvious one is the line length. Linters usually set this to 79. I find it way to short, but I am open to discussions about this.

Then, I had to ignore several issues for flake8:
- you are using a C++ naming convention. I hate that, but I will not try to make you change this, so these are disabled:
    - N802: function name should be lowercase
    - N803: argument name should be lowercase
    - N806: variable in function should be lowercase
- ~~you are assigning lambda expressions everywhere, I don't understand why. As it would require more work to fix this, I disabled:~~
    - ~~E731: do not assign a lambda expression, use a def~~
- ~~I was a bit lazy about those, but I should be able to fix them soon (so this PR is in WIP state):~~
    - ~~E722: do not use bare except, specify exception instead~~
    - ~~E741: do not use variables named ‘l’, ‘O’, or ‘I’~~
    - ~~W504: line break after binary operator~~

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 11, 2019, 13:03

changed the description

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 11, 2019, 15:30

added 4 commits

<ul><li>9a46e00d - [Format] fix E741</li><li>f2f48f20 - [Format] fix W504</li><li>4b88ebb2 - [Format] fix E722</li><li>d60178cf - [Format] fix E731</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=662&start_sha=aa6b479a7dd12f5b9e79b6216cd5fc1931875ebf)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 11, 2019, 15:32

added 1 commit

<ul><li>7d948652 - [Format] fix isort</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=663&start_sha=d60178cf21f4205eccab9d687a0ba0117de67935)

**Comment by wxmerkt** [comment]
In GitLab by @proyan on Mar 11, 2019, 15:42

This may be a silly question, but does this mean that all future commits will need to conform to the formatting of isort, flake8 and yapf?

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 11, 2019, 16:37

Yes. The general idea is that it is useless to reformat this if we don't enforce subsequent commits to comply with the new format.

But we can discuss about which and how many tools we should use for the format of this project.

Also, when we will start to add c++ code, I think we will have to add other tools, like clang-tidy & clang-format.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 11, 2019, 16:40

Please note that this is a separate test, meaning that you can work in your fork / on the branch of your choice, and make / push several commits, while just checking that the tests are not unexpectedly broken, and ignoring the format.
When you are done with it, you can look at the results of the `format` CI check, and reformat stuff as needed in one commit before creating a MR.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 13, 2019, 15:48

added 5 commits

<ul><li>7d948652...3269cf78 - 4 commits from branch <code>loco-3d:devel</code></li><li>fee8d727 - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=676&start_sha=7d948652beb23f12a9fcc08711b3f52ef74ed79e)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 13, 2019, 15:50

unmarked as a **Work In Progress**

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 13, 2019, 15:53

Flake8 flags E722, E731, E741 & W504 have been fixed. I'm ready to merge it, if you don't need to discuss this more.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 08:54

We don't need anymore talos-data. Maybe we should remove it in this PR.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 09:06

I also agree that we shouldn't use lambda functions. However this can be tackle in a next PR.

I have two questions:
 1. what is the maximum line length allowed?
 2. how should we test our format code before PR? is there a run script here?

I think point 2 is important, every developer should know how to test his/her format. I would like to avoid people creating commits after CI complains. We should have a documented policy that it can be added in this PR.

@nim65s could you rebase your PR? I apologize if we don't tackle before, let's try to merge it today.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:09

changed this line in [version 5 of the diff](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=679&start_sha=fee8d7278719f44dd427912e9c451c564742ae22#6651ddff6eb82c840ced7c1dddee15c6e1913dd4_11_11)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:09

added 1 commit

<ul><li>1a472946 - [CI] no more need for the private talos-data dependency</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=679&start_sha=fee8d7278719f44dd427912e9c451c564742ae22)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:09

Nice catch, thanks :)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:15

I already fixed the named lambdas in d60178cf.

1. The maximum line length allowed has been set to 119 in this PR. By default, it would have been 79.
2. To test the format, you can run the same commands as in the CI:
    - `isort -c`
    - `flake8 .`
    - `yapf -dr .`

    These commands can be run automatically in your IDE, but if you don't want to spend time to configure it, I understand that this is not easy enough.

    Maybe I can add a make target that run all of these.

    What do you think ?

I will not rebase it as it would be too much work, but merge devel in it instead.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:19

added 8 commits

<ul><li>1a472946...f1f8858c - 7 commits from branch <code>loco-3d:devel</code></li><li>5337db6d - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=680&start_sha=1a47294660aa5b988a7c3d62e7e82de1301777ad)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 15, 2019, 09:24

changed the description

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 09:25

I think this discussion is resolved. Feel free to re-open it.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 09:25

resolved all discussions

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 15, 2019, 13:24

I have detected an issue in this PR. I have fixed here https://gepgitlab.laas.fr/gsaurel/crocoddyl/merge_requests/1. @nim65s please have a look on it, let me know how to solve the format issue. For some reason, isort doesn't trigger it in my PC

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 22, 2019, 18:48

added 7 commits

<ul><li>3303bebc - [bugfix] Removed wrong module inclusion in the bipedal example</li><li>7d44368c - [bugfix] Updated the CallbackDDPVerbose inside unicycle notebook</li><li>bcf9c3fa - [bugfix] Fixed error with the display</li><li>7f6bf4c9 - [bugfix] Added a missed module</li><li>842a8c04 - [bugfix] Passed isort, I hope this works</li><li>11cc2c39 - [isort] Done for python scripts inside notebooks folder</li><li>77907f20 - Merge branch &#39;topic/format&#39; into &#39;topic/format&#39;</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=720&start_sha=5337db6dcc008c8d76e630a8ed401b21642e5cf1)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 22, 2019, 19:12

added 1 commit

<ul><li>b799b827 - [CI] remove isort</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=721&start_sha=77907f207198594f63890053116acf062afa8ea0)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 22, 2019, 19:13

added 1 commit

<ul><li>a3f43285 - [Style] fix flake8</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=722&start_sha=b799b8277b58c650ad5b39d22304c1d9b2efc42c)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 22, 2019, 19:31

added 25 commits

<ul><li>a3f43285...0f50baa1 - 23 commits from branch <code>loco-3d:devel</code></li><li>f9b7662a - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li><li>1e5760d1 - [Style] Ignore sandbox</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=723&start_sha=a3f43285cff55c22ec69c6383d720d9cc5663d65)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 22, 2019, 19:33

LGTM, feel free to merge if needed :)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 23, 2019, 08:15

added 11 commits

<ul><li>1e5760d1...77c18f36 - 10 commits from branch <code>loco-3d:devel</code></li><li>6b7d3a7b - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=724&start_sha=1e5760d10095379ad483eb09a5763d903beead56)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 23, 2019, 08:36

added 1 commit

<ul><li>0c565b76 - [Tests] add . to PYTHONPATH for ctest</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=725&start_sha=6b7d3a7bfddeb8b7b7f400e1079f45030be3e84f)

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 27, 2019, 11:48

@nim65s I agree with 79 charateres is too short, however it might be too long 119. What about 99?

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 27, 2019, 11:53

I think this kind of details should be discussed for the whole team, not just on this project.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Mar 27, 2019, 11:56

I agree, did you already discuss it? Probably we should have two different answers for Python and c++.

I would like to define c++ standards before starting to c++ version. And as a consequence, to enable it from the very beginning

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 27, 2019, 11:59

C++ linters are already run on this project, starting from this PR, that's the `check-clang-format.sh` in https://gepgitlab.laas.fr/gsaurel/crocoddyl/-/jobs/15850 which just show that it can't find any C++ header or source for now.

This comes from there: https://gepgitlab.laas.fr/gepetto/linters

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Mar 28, 2019, 12:19

added 5 commits

<ul><li>0c565b76...2fb8a27b - 4 commits from branch <code>loco-3d:devel</code></li><li>92ea2532 - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=744&start_sha=0c565b764bd259e2b5a0298e0672b0b3edca3230)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 3, 2019, 15:46

added 17 commits

<ul><li>92ea2532...c91c4c40 - 15 commits from branch <code>loco-3d:devel</code></li><li>934c841c - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li><li>6e5ae36b - [format] fix flake8</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=783&start_sha=92ea253267b990e0c50a0fbaa3c7face61ab3a9d)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 4, 2019, 11:40

added 34 commits

<ul><li>6e5ae36b...7e160284 - 31 commits from branch <code>loco-3d:devel</code></li><li>acf55086 - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li><li>c831ba7b - [format] fix flake8</li><li>5422c90c - [CI] add quadprog to docker image</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=789&start_sha=6e5ae36beef13741242867b11c13ce68a3012186)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 4, 2019, 12:01

added 1 commit

<ul><li>ec6021eb - fix imports</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=790&start_sha=5422c90cddcc10d22cd53ba9d7350ec20e46d1d5)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 4, 2019, 13:20

added 6 commits

<ul><li>1560adc1 - [CMake] update tests</li><li>1e46715e - fix catch_warnings</li><li>e5bbdad7 - [CMake] add locomotion</li><li>ba80bcb7 - [CI] add multicontact-api to docker image</li><li>226f9633 - [Tests] locomotion: fix multicontact_api import &amp; path to xml file</li><li>7dc136dd - [CMake] set dependencies</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=792&start_sha=ec6021eb899943325e037dd0bd78f2870eb53efe)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 4, 2019, 14:14

I updated this MR a bit, and a few tests are failing. At this point, after so many merges, it is becoming hard for me to find if an issue comes from one of the merge I did or from somewhere else. These issues, shown in https://gepgitlab.laas.fr/gsaurel/crocoddyl/-/jobs/16940 are the following:

```
 4/17 Test  #5: py-boxsolvers ....................***Failed    0.46 sec
Traceback (most recent call last):
  File "/builds/gsaurel/crocoddyl/unittest/test_boxsolvers.py", line 83, in <module>
    assert (uddp_box[0][limit_id] == ddpbox.ul[limit_id])
AssertionError
```

```
 5/17 Test  #7: py-costs .........................***Failed    0.40 sec
Traceback (most recent call last):
  File "/builds/gsaurel/crocoddyl/unittest/test_costs.py", line 173, in <module>
    NUMDIFF_MODIFIER * costModelND.disturbance)  # threshold was 1e-4, is now 2.11e-4 (see assertNumDiff.__doc__)
  File "/builds/gsaurel/crocoddyl/unittest/testutils.py", line 23, in assertNumDiff
    raise NumDiffException("NumDiff exception, with residual of %.4g, above threshold %.4g" % (value, threshold))
testutils.NumDiffException: NumDiff exception, with residual of 3.119, above threshold 0.0002107
```

```
 9/17 Test #10: py-dynamic_derivatives ...........***Failed    0.61 sec
Traceback (most recent call last):
  File "/builds/gsaurel/crocoddyl/unittest/test_dynamic_derivatives.py", line 450, in <module>
    KJn = K * dcid_dqn
  File "/usr/lib/python2.7/dist-packages/numpy/matrixlib/defmatrix.py", line 343, in __mul__
    return N.dot(self, asmatrix(other))
ValueError: shapes (13,13) and (10,7) not aligned: 13 (dim 1) != 10 (dim 0)
```

```
13/17 Test #12: py-locomotion ....................***Exception: Other  1.48 sec
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
```

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 4, 2019, 14:32

Scipy isn't optional one.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 4, 2019, 14:34

Yes, but it doesn't provide a .pc, so if we put a `REQUIRED`, CMake will fail. 
I will handle this later, this is just a placeholder to remind that scipy is indeed a dependency

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 4, 2019, 14:35

Ok, you know your business.

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 4, 2019, 14:35

resolved all discussions

**Comment by wxmerkt** [comment]
In GitLab by @cmastalli on Apr 4, 2019, 15:06

@nim65s You have four type of errors:
 1. Regarding box DDP (1 message, PR !129)
 2. Regarding NumDiff changes (!121) (2 message, PR !121)
 3. Unknown for me (3 message)
 4. Regarding multicontact-api (4 messages)

I would comment each one. In any case all the unit-test are passing (devel branch), with the exception of test_locomotion. I reported this issue here #154, maybe @nmansard could help with this.

---
**Box DDP**:

I have no idea how it's happening here, @proyan is your guy.

---
**NumDiff**:

Inspecting your branch, I see that there is a missing piece of code before the failing assertNumDiff, i.e.:

```python
costModelND = CostModelNumDiff(costModel,StatePinocchio(rmodel),withGaussApprox=True,
                               reevals = [ lambda m,d,x,u: pinocchio.forwardKinematics(m,d,a2m(x[:rmodel.nq]),a2m(x[rmodel.nq:])),
                                           lambda m,d,x,u: pinocchio.computeJointJacobians(m,d,a2m(x[:rmodel.nq])),
                                           lambda m,d,x,u: pinocchio.updateFramePlacements(m,d) ])
costDataND  = costModelND.createData(rdata)

costModelND.calcDiff(costDataND,x,u)
...
# then the asserts
```
**Did you get merge conflicts? Could be possible just re-run the formater from devel branch + plus adding CI setups?** (instead of merging devel into this branch). I'm trying to figure out the less risky and easiest way of doing this.

---
**Unknown error**:

Since I saw missing code, I suspect that here is passing the same. I believe recent PRs aren't connected with this.

--
**Multicontact-API**:

This error is weird and it's not connected with #154 (another one). Maybe merge request conflicts? In any case, we should tackle #154.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 09:09

added 1 commit

<ul><li>9395362c - fix merges</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=793&start_sha=7dc136ddd36d89cf20262dd51684a74e52689461)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 09:09

Thanks, I should have figured out how to fix this. the 3 first errors have been fixed.

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 09:23

added 1 commit

<ul><li>16a70c8b - [Format] fix flake8 with functools.partial</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=794&start_sha=9395362c649856ef3e4dd59cafea7b390162efa5)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 17:29

added 12 commits

<ul><li>16a70c8b...9c22a62d - 9 commits from branch <code>loco-3d:devel</code></li><li>87d47fcf - Merge remote-tracking branch &#39;main/devel&#39; into topic/format</li><li>bc471035 - [Format] sandbox/expect</li><li>fc3da4b2 - [Tests] disable locomotion for now</li></ul>

[Compare with previous version](https://gepgitlab.laas.fr/loco-3d/crocoddyl/merge_requests/137/diffs?diff_id=796&start_sha=16a70c8ba169fbb2f1bffa219d3a8aa5077abbf0)

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 17:30

merged

**Comment by wxmerkt** [comment]
In GitLab by @nim65s on Apr 5, 2019, 17:30

mentioned in commit d42e2654ebabf92d7bc7b693158987459274bf07
