### ISSUE TITLE
conda installation for devel branch

### ISSUE THREAD

**Issue by ddliu365** [loco-3d/crocoddyl#956]
Hi,

I need to use the crocoddyl  devel version in a conda environment.

I tried to directly replace the crocoddyl folder in conda with the package in the build folder after building from source, but it doesn't work and it raises the following error:
```
>>> import crocoddyl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ext3/miniconda3/envs/LDD/lib/python3.6/site-packages/crocoddyl/__init__.py", line 5, in <module>
    import pinocchio
  File "/ext3/miniconda3/envs/LDD/lib/python3.6/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
SystemError: initialization of pinocchio_pywrap raised unreported exception
```

but if the pinocchio is imported first and then crocoddyl, the error will be changed
```
>>> import pinocchio
>>> import crocoddyl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ext3/miniconda3/envs/LDD/lib/python3.6/site-packages/crocoddyl/__init__.py", line 1, in <module>
    from .libcrocoddyl_pywrap import *
SystemError: initialization of libcrocoddyl_pywrap raised unreported exception
```

It may be caused by the dependency order issue of conda. Is there a way to use the devel branch in conda without waiting the next release version?

**Comment by proyan** [comment]
You need to fix your installation, I'm sorry the problem lies in your machine, I believe that you have a duplicate installation somewhere. I'll close this issue.
